# Generated by Django 4.2.1 on 2023-09-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff_member_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please Enter Staff Member Name', max_length=180, unique=True)),
                ('email', models.EmailField(help_text='Please Enter Staff Member Email', max_length=180)),
                ('mobile', models.CharField(help_text='Please Enter Staff Member 10 digit Phone Number', max_length=10)),
                ('image', models.ImageField(help_text='Please Enter Staff Member Image', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='visitor_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please Enter Visitor Name', max_length=180, unique=True)),
                ('email', models.EmailField(help_text='Please Enter Visitor Email', max_length=180)),
                ('mobile', models.CharField(help_text='Please Enter Visitor 10 digit Phone Number', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='visitor_detail_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Please Enter Reason', max_length=256)),
                ('state', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('staff_member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.staff_member_model', to_field='name')),
                ('visitor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor_model', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='drink_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please Enter Drink Name', max_length=180)),
                ('serve_member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.staff_member_model', to_field='name')),
            ],
        ),
    ]
