# Generated by Django 4.2.1 on 2023-09-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink_model',
            name='name',
            field=models.CharField(help_text='Please Enter Drink Name', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor_detail_model',
            name='state',
            field=models.CharField(default='Inprogress', help_text='Please Leave This Field as it is', max_length=20),
        ),
        migrations.CreateModel(
            name='visitor_drink_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='Inprogress', help_text='Please Leave This Field as it is', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drink_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.drink_model', to_field='name')),
                ('visitor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor_model', to_field='name')),
            ],
        ),
    ]
